version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  draintimeout: 60s
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /etc/certs/vps2.nilstrieb.dev.crt
    key: /etc/certs/vps2.nilstrieb.dev.key
auth:
  htpasswd:
    realm: nilstrieb-registry
    path: /htpasswd
