apiVersion: apps/v1
kind: Deployment
metadata:
  name: karin
spec:
  selector:
    matchLabels:
      app: karin
  replicas: 1
  template:
    metadata:
      labels:
        app: karin
    spec:
      containers:
      - name: court-bot
        image: discord-court-bot:1.0
        envFrom:
          - configMapRef:
              name: karin
          - secretRef:
              name: karin
          - secretRef:
              name: mongodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karin
data:
  RUST_LOG: DEBUG
  GUILD_ID: "459006129670979584"
  DB_NAME: karin
  SET_GLOBAL: ''