version: "3.8"
services:
  uptime:
    container_name: uptime
    image: "docker.nilstrieb.dev/uptime:1f89aae3"
    restart: always
    volumes:
      - "/apps/uptime:/app/config"
    environment:
      UPTIME_CONFIG_PATH: /app/config/uptime.json
    ports:
      - "5010:3000"
  ##### openolat
  openolat_db:
    container_name: openolat-db
    image: "postgres:latest"
    restart: always
    volumes:
      - "/apps/openolat/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: oodb
      POSTGRES_USER: oodbu
      POSTGRES_PASSWORD: "${OPENOLAT_DB_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - openolat-network
  openolat:
    container_name: openolat
    image: "docker.nilstrieb.dev/openolat:d8b5cd90"
    restart: always
    volumes:
      - "/apps/openolat/olatdata:/home/openolat/olatdata"
      - "/apps/openolat/extra-properties.properties:/home/openolat/extra-properties.properties"
    ports:
      - "5011:8088"
    environment:
      DB_PASSWORD: "${OPENOLAT_DB_PASSWORD}"
      DB_URL: "jdbc:postgresql://openolat-db:5432/oodb"
      EXTRA_PROPERTIES: "/home/openolat/extra-properties.properties"
      OLAT_HOST: olat.nilstrieb.dev
    networks:
      - openolat-network

networks:
  openolat-network: