version: "3.8"
services:
  uptime:
    container_name: uptime
    image: "docker.nilstrieb.dev/uptime:f12b6ffa"
    restart: always
    volumes:
      - "/apps/uptime:/app/config"
    environment:
      UPTIME_CONFIG_PATH: /app/config/uptime.json
    ports:
      - "5010:3000"

networks: {}
