version: '3.8'
services:
  registry:
    container_name: registry
    restart: always
    image: registry:2
    volumes:
      - "/apps/registry/config.yml:/etc/docker/registry/config.yml"
      - "/apps/registry/data:/var/lib/registry"
      - "/apps/registry/htpasswd:/htpasswd"
    ports:
      - "5000:5000"

# TODO: create an internal network and move caddy there as well.
