version: "3.8"
services:
  registry:
    container_name: registry
    restart: always
    image: registry:2
    volumes:
      - "/apps/registry/config.yml:/etc/docker/registry/config.yml"
      - "/apps/registry/data:/var/lib/registry"
      - "/apps/registry/htpasswd:/htpasswd"
    ports:
      - "5000:5000"
  widetom:
    container_name: widetom
    image: "docker.nilstrieb.dev/widetom:490c94ca"
    restart: always
    volumes:
      - "/apps/widetom:/app/config"
    environment:
      CONFIG_PATH: /app/config/config.toml
      BOT_TOKEN_PATH: /app/config/bot_token
  killua:
    container_name: killua
    image: "docker.nilstrieb.dev/killua-bot:ac8203d2"
    restart: always
    volumes:
      - "/apps/killua:/app/config"
    environment:
      BOT_TOKEN: "${KILLUA_BOT_TOKEN}"
      KILLUA_JSON_PATH: /app/config/trivia_questions.json
  hugo_chat_db:
    container_name: hugo-chat-db
    image: "postgres:latest"
    restart: always
    # no ports bound, accessed via the internal network
    environment:
      POSTGRES_PASSWORD: "${HUGO_CHAT_DB_PASSWORD}"
    networks:
      - internal
  hugo_chat_server:
    container_name: hugo-chat-server
    image: "docker.nilstrieb.dev/hugo-chat-server:63bd1922"
    ports:
      - "5001:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hugo-chat-db:5432/postgres"
      SPRING_DATASOURCE_PASSWORD: "${HUGO_CHAT_DB_PASSWORD}"
    networks:
      - internal
  hugo_chat_client:
    container_name: hugo-chat-client
    image: "docker.nilstrieb.dev/hugo-chat-client:63bd1922"
    restart: always
    ports:
      - "5002:80"
  karin_bot_db:
    container_name: karin-bot-db
    image: "mongo:latest"
    restart: always
    env_file:
      - "/apps/karin-bot/.env"
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
  karin_bot:
    container_name: karin-bot
    image: "docker.nilstrieb.dev/discord-court-bot:921be642"
    restart: always
    env_file:
      - "/apps/karin-bot/.env"
    networks:
      - internal
networks:
  internal:
