---
- name: Generic setup
  ansible.builtin.import_playbook: ./basic-setup.yml
- name: VPS 2 setup
  hosts: vps2
  gather_facts: false
  tasks:
    - name: Install htpasswd
      ansible.builtin.apt:
        name: apache2-utils
    #####
    # APP: docker registry, /apps/registry
    #####
    - name: Create /apps/registry
      ansible.builtin.file:
        path: /apps/registry
        state: directory
        mode: u=rwx,g=rx,o=rx
    - name: Create /apps/registry/data
      ansible.builtin.file:
        path: /apps/registry/data
        state: directory
        mode: u=rwx,g=rx,o=rx
    - name: Copy over registry config.yml
      ansible.builtin.copy:
        dest: /apps/registry/config.yml
        src: ../apps/registry/config.yml
        mode: u=r,g=r,o=r # readonly
    #####
    # APP: docker registry, /apps/registry
    #####
    - name: Create /apps/widetom
      ansible.builtin.file:
        path: /apps/registry
        state: directory
        mode: u=rwx,g=rx,o=rx
    #####
    # END: docker compose up!
    #####
      # We want this to be last so that all app-specific config has been done.
    - name: Docker compose up! 🚀
      community.docker.docker_compose:
        project_src: /apps
        state: present
        restarted: true
