- name: "Init Cluster"
  block:
    - name: Wait for everything to start up
      # TODO Wait for the coredns pods to be Pending
      ansible.builtin.command: "false"
      changed_when: false
    - name: Apply Flannel
      ansible.builtin.command:
        cmd: kubectl apply -f https://github.com/flannel-io/flannel/releases/download/v0.24.2/kube-flannel.yml
      changed_when: true
    - name: Give it some time to breathe
      ansible.builtin.command:
        cmd: sleep 30
      changed_when: false
    - name: Allow scheduling on the control plane
      ansible.builtin.command:
        cmd: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      changed_when: true
    - name: Start nginx test containers
      ansible.builtin.command:
        cmd: kubectl apply -f /root/nginx-test.yaml
      changed_when: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
