---
- name: VPS 1 setup
  hosts: vps1
  gather_facts: false
  tasks:
    #####
    # APP: uptime, /apps/uptime
    #####
    - name: Create /apps/uptime
      ansible.builtin.file:
        path: /apps/uptime
        state: directory
        mode: "u=rwx,g=rx,o=rx"
    - name: Copy uptime.json
      ansible.builtin.copy:
        dest: /apps/uptime/uptime.json
        src: ../apps/uptime/uptime.json
        mode: "u=r,g=r,o=r"
    #####
    # END: docker compose up!
    #####
      # We want this to be last so that all app-specific config has been done.
    - name: Copy .env
      ansible.builtin.copy:
        dest: "/apps/.env"
        src: "../secrets/vps1.env"
        mode: "u=r,g=r,o=r"
    - name: Docker compose up! 🚀
      community.docker.docker_compose:
        project_src: /apps
        restarted: true
